config/routes.rb
Rails.application.routes.draw do
  resources :keywords

  root 'keywords#index'

end

app/models/keyword.rb
class Keyword < ActiveRecord::Base
  has_many :tweets

  def grab_tweets
    client = Twitter::REST::Client.new do |config|
      config.consumer_key = ENV['TWITTER_CONSUMER_KEY']
      config.consumer_secret = ENV['TWITTER_CONSUMER_SECRET']
      config.access_token = ENV['TWITTER_OAUTH_KEY']
      config.access_token_secret = ENV['TWITTER_OAUTH_TOKEN_SECRET']
    end

    client.search(self.word, :count => 100, :result_type => "recent").take(100).collect do |tweet|
      new_tweet = Tweet.new

      new_tweet.tweet_id = tweet.id.to_s
      new_tweet.text = tweet.text
      new_tweet.tweet_created_at = tweet.created_at

      new_tweet.user_uid = tweet.user.id
      new_tweet.user_name = tweet.user.name
      new_tweet.user_screen_name = tweet.user.screen_name
      new_tweet.user_image_url = tweet.user.profile_image_url

      new_tweet.keyword = self

      new_tweet.save
    end
  end

  def self.grab_all_tweets 
    Keyword.all.each do |keyword|
      keyword.grab_tweets
    end
  end
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :keyword
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
  before_action :set_keyword, only: [:show, :edit, :update, :destroy]

  # GET /keywords
  # GET /keywords.json
  def index
    @keywords = Keyword.all
  end

  # GET /keywords/1
  # GET /keywords/1.json
  def show
    @tweets = @keyword.tweets.paginate(page: params[:page], per_page: 100).order('created_at DESC')
  end

  # GET /keywords/new
  def new
    @keyword = Keyword.new
  end

  # GET /keywords/1/edit
  def edit
  end

  # POST /keywords
  # POST /keywords.json
  def create
    @keyword = Keyword.new(keyword_params)

    respond_to do |format|
      if @keyword.save
        
        @keyword.grab_tweets

        format.html { redirect_to @keyword, notice: 'Keyword was successfully created.' }
        format.json { render :show, status: :created, location: @keyword }
      else
        format.html { render :new }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /keywords/1
  # PATCH/PUT /keywords/1.json
  def update
    respond_to do |format|
      if @keyword.update(keyword_params)
        format.html { redirect_to @keyword, notice: 'Keyword was successfully updated.' }
        format.json { render :show, status: :ok, location: @keyword }
      else
        format.html { render :edit }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /keywords/1
  # DELETE /keywords/1.json
  def destroy
    @keyword.destroy
    respond_to do |format|
      format.html { redirect_to keywords_url, notice: 'Keyword was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_keyword
      @keyword = Keyword.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def keyword_params
      params.require(:keyword).permit(:word)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/views/keywords/_form.html.erb
<%= form_for(@keyword) do |f| %>
  <% if @keyword.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@keyword.errors.count, "error") %> prohibited this keyword from being saved:</h2>

      <ul>
      <% @keyword.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :word %><br>
    <%= f.text_field :word %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/keywords/edit.html.erb
<h1>Editing Keyword</h1>

<%= render 'form' %>

<%= link_to 'Show', @keyword %> |
<%= link_to 'Back', keywords_path %>

app/views/keywords/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Listing Keywords</h2>

<table>
  <thead>
    <tr>
      <th>Word</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @keywords.each do |keyword| %>
      <tr>
        <td><%= keyword.word %></td>
        <td><%= link_to 'Show', keyword %></td>
        <td><%= link_to 'Edit', edit_keyword_path(keyword) %></td>
        <td><%= link_to 'Destroy', keyword, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Keyword', new_keyword_path %>

app/views/keywords/new.html.erb
<h1>New Keyword</h1>

<%= render 'form' %>

<%= link_to 'Back', keywords_path %>

app/views/keywords/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Word:</strong>
  <%= @keyword.word %>
</p>

<h2>Latest Tweets (<%= @tweets.count %>)</h2>
<ul>
	<% @tweets.each do |tweet| %>
		<li><img src="<%= tweet.user_image_url %>" width="30"> <%= tweet.user_screen_name %>: <%= tweet.text %></li>
	<% end %>		
</ul>

<%= will_paginate @tweets %>

<%= link_to 'Edit', edit_keyword_path(@keyword) %> |
<%= link_to 'Back', keywords_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tweetitor</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1>Tweetitor</h1>
<hr>

<%= yield %>

<hr>
<div style="text-align:center">Tweetitor</div>

</body>
</html>